[package]
name = "openrgb-fade"
version = "0.1.0"
edition = "2024"

[dependencies]
hidapi = "2.6.3"
openrgb2 = "0.3.0"
rusb = "0.9.4"
tokio = { version = "1.48.0", features = ["macros", "time", "rt"] }
